### ISSUE TITLE
Send message to live chat not working

### ISSUE THREAD

**Issue by zzyzx13** [bitfocus/companion-module-youtube-live#103]
Using whatever version of the module comes with Companion 3.1.2 (3.1.2+6243-stable-05c37a10)

Even when using a fresh module with new authentication.

![IMG_0919](https://github.com/bitfocus/companion-module-youtube-live/assets/97838246/67e8f4d4-5c88-4eaa-84b9-2e76780c0877)

I will soon be testing a rollback to Companion 2.4.2 to see if that resolves the issue.

**Comment by cyprient** [comment]
Hello @zzyzx13 ! I just tested the feature with Companion 3.1.2 and it worked fine. You must select the `Unfinished/planned #0` broadcast to make it works. Also, do not hesitate to `Refresh everything from YouTube` when you go live in order to update the data of the module.
