### ISSUE TITLE
Feature Request: add YouTube stream ID as a user variable

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion-module-youtube-live#105]
Currently there are variables telling me the state and health of all my unfinished/planned broadcasts, generically numbered 0, 1, 2, ...

There are also variables that tell me the same information, in variables whose names include the YouTube stream ID:
`$(YouTube:broadcast_KByv3z2mjfE_health) | Health of the stream bound to broadcast titled 'test upcoming stream'
`

What I would like, is to have for (at least) each of the unfinished/planned broadcasts, is a variable named something like 
`$(YouTube:unfinished_broadcastID_0)`
In the example above it would be assigned a value of `KByv3z2mjfE`

Use case: I would like to be able to dynamically build the specific URL of the current live stream, into a string to be loaded in a browser or other streaming device

P.S. I thought I already submitted a very similat request in the lase week or so but I don't see it. I apologize if this is a duplicate!

**Comment by josephdadams** [comment]
I added this in commit 385a2ad, pushed it to module version v2.4.2, and put it in the betas
