### ISSUE TITLE
Control Other Youtube Channels

### ISSUE THREAD

**Issue by pmc4060** [bitfocus/companion-module-youtube-live#108]
Not necessary an issue but is it possible to set up the connection to control a different account that my personal account has access to?

-Module setup using my personal gmail / youtube account
- I can control content on my youtube channel (Phillip Cooper)

Can I change this to one of the other youtube accounts that i manage? (Cheshire Scouts Or Chamboree)

Is this possible or is there any guidance for this? 

Thanks

<img width="299" alt="Screenshot 2024-02-10 at 19 58 29" src="https://github.com/bitfocus/companion-module-youtube-live/assets/108198671/9a1f279d-d849-4f1a-93b8-8917c118fd53">

**Comment by pmc4060** [comment]
Having taken another look at this the other accounts are "Brand Accounts" so dont have their own gmail log in. 

I found this https://stackoverflow.com/questions/41016537/youtube-apis-access-mutiple-youtube-channels-brand-accounts-using-google-adm  

& https://gist.github.com/veuncent/e0b831ab41d598961d2656c7fc5cc0f9


showing how to add the api for a brand account but as a none workspace user i don't  know how to add the developer oauthplayground credentials into the oauth 2.0 app to reference the brand account. 

It would be great if this was something that could be done in companion and if there was a step by step

**Comment by cyprient** [comment]
Hello @pmc4060,
When you configure the YT instance in Companion, you must be able to select the other channels.
For now, each module instance can only control one channel at a time. But a workaround is to create multiple YT instances in Companion (one for each channel).
I will close this issue, but do not hesitate to reopen it if you have any issue.
