### ISSUE TITLE
ISC vs MIT License

### ISSUE THREAD

**Issue by JakubVanek** [bitfocus/companion-module-youtube-live#12]
Hi!

there are currently two licenses in this repository:
 * `package.json` contains `"license": "ISC"`, but
 * `LICENSE` contains the MIT license.

While these licenses seem to be equivalent, which of these should be taken as the main one?

Thanks!

Jakub

**Comment by haakonnessjoen** [comment]
MIT is preferred

**Comment by melimat** [comment]
Done, thanks for notice, I really appreciate that.
