### ISSUE TITLE
Refactor/rewrite ideas

### ISSUE THREAD

**Issue by JakubVanek** [bitfocus/companion-module-youtube-live#42]
Ideas:
 - introduce/define object model (YtBroadcast, YtStream)
 - rewrite using TypeScript (?)
 - make youtube handler stateless with regard to query operations (no embedded broadcast list)
   - youtube authorization data have to be stateful
 - make separate youtube state class (containing state moved from youtube handler)
 - separate authorization flow to its own class

**Comment by JakubVanek** [comment]
- add asynchronous action abstraction (i.e. broadcast switching)

**Comment by JakubVanek** [comment]
but before all, Maturita exam FTW

**Comment by JakubVanek** [comment]
- split module into multiple files

**Comment by JakubVanek** [comment]
- make data structures immutable

**Comment by krocheck** [comment]
I'd recommend an ES6 class refactor.  Its quicker and makes splitting the files easier.

**Comment by JakubVanek** [comment]
- introduce unit tests
  - find out how it's done in JS
  - find out how Companion fits into it
