### ISSUE TITLE
Upcoming streams IDS in variables

### ISSUE THREAD

**Issue by jendamozna** [bitfocus/companion-module-youtube-live#62]
Would it be is possible to have following?

Variables:
{yt:upcoming_stream_1} - My stream 1
{yt:upcoming_stream_2} - Another stream name
{yt:upcoming_stream_3} - N/A
... e.g. up to 10
{yt:upcoming_stream_id_1} - asdfasdfasdf
{yt:upcoming_stream_id_2} - sdfgsdfgsdfg
{yt:upcoming_stream_id_3} - N/A
...

Actions:
YT: Start Upcoming Stream
-- input param select box containing: upcoming_stream_1, upcoming_stream_2, upcoming_stream_3, ...

YT: Stop Stream by ID
-- input param streamId

Feedback:
YT: Stream State by ID
-- input param streamId
-- states: live/active, completed/finished, ... 

This would help in my usecase, where i could map first few streams into fixed buttons and use them without need of manualy assigning buttons in companion before action.

**Comment by jendamozna** [comment]
implemented in https://github.com/bitfocus/companion-module-youtube-live/pull/64

**Comment by whizkidTRW** [comment]
I’m very excited to test this out just as soon as I can!

**Comment by starsolutions** [comment]
Also excited to test this too! Setup the dev environment so I could build it and give it a try tomorrow.

**Comment by Gartom** [comment]
> 
> 
> prepared in #64

Great work, will try this when I have time.
