### ISSUE TITLE
Automatically switch to newest created Live-stream

### ISSUE THREAD

**Issue by LoadingUser404** [bitfocus/companion-module-youtube-live#71]
Hello,

We are using a stream-deck with companion to run a YouTube live-stream each Sunday morning.
We would like to use the button on the YT Module for companion to toggle Go Live on YouTube remotely from the stream deck.

Was wondering if there was any way to make that button automatically Refer to the newest made live-stream instead of changing the settings each time we want to go live with a different stream.

Thanks very much,
-GitHub User :)

**Comment by jendamozna** [comment]
Hi, yes, its already implemented https://github.com/bitfocus/companion-module-youtube-live/pull/63 
There is special action "Go live" where you can set "Unfinished #0" as its param and it will be mapped to the nearest upcomming pending stream, so you dont need to reconfigure buttons every week.

You can also use various variables to see upcoming stream state: $(YT:unfinished_0), $(YT:unfinished_health_0), $(YT:unfinished_state_0)

**Comment by LoadingUser404** [comment]
Thanks so much!
