### ISSUE TITLE
unfinished_x variable is periodically wrong

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion-module-youtube-live#78]
I currently have two scheduled YT live events ("Ready" state) and hundreds if past live streams.

I have my "Interval between refreshments of broadcasts statuses and streams health (in seconds)" set to 30.

Every 30 seconds my unfinished_0 variables will change to incorrectly reflect the title and status of a particular completed video, and the remaining unfinished_x variables say "n/a."  5 seconds later, the unfinished_0 and unfinished_1 variables will revert to the correct information and remain there until the next 30-second cycle.

I've tried changing the interval value with interesting results: the cycle time changes to whatever number I input, but the amount of time that the wrong information remains in the variables changes to a new value.  For example, after changing the interval value to 45 and later back to 30, the wrong information is reflected in the variables for almost 10 seconds of each cycle.

So I implemented another instance of the module into Companion.  This seems to have eliminated the symptoms but I'm concerned about them returning, and I didn't really fix anything.

I did have (but have removed, today) some automation which would disable and then re-enable the module once a week. I don't remember why that was in there, perhaps an attempt to solve this problem.

**Comment by jendamozna** [comment]
Whats is your setting for:
- How many broadcasts to fetch from YouTube
- How many unfinished/planned broadcasts store into unfinished_* variables

Create an action button: Reload everything from YouTube
- Does is behaves better when pressed?

Any warning in the logs tab?

**Comment by mark-epstein** [comment]
No warnings in the log file.

I tried numerous varied settings for the "how many" questions, as high as 20/5 and as low as 1/1, always with the same result.

I already do a "reload everything" at least once a week, because I have a button which uses the name of unfinished_0 as the text for that button. We do streams once a week, so we use this to make sure that the YouTube title is correct.  I don't recall it making a difference in the past, and the problem persisted for several weeks. I want make an effort to test it explicitly, but...

Moving everything back to the original YouTube instance (I had only disabled, not deleted it) I find that it now doesn't show any of the prior symptoms.

**Comment by mark-epstein** [comment]
^ I guess I forgot to add... I'm not sure if this issue should remain open since I can no longer reproduce the problem. I'm sure whatever bug I encountered still exists, but without some smoke it's going to be hard to find a fire, let alone know if the problem has truly been resolved. I'll leave it up to y'all to close as you see fit.

**Comment by mark-epstein** [comment]
well, it's been a year and I haven't had any recurrence of this issue, so I'm going to close this
