### ISSUE TITLE
feature request: post messages to YouTube chat

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion-module-youtube-live#95]
I would love to be able to hit a Companion button and have it post a message in the live chat.
Ideally the content could come from a variable.

**Comment by obcocav** [comment]
This would be great!

**Comment by cyprient** [comment]
This feature was already integrated in the version 2.0 of the module, which is available in Companion v3.

**Comment by mark-epstein** [comment]
d'oh! I should have checked. I haven't upgraded my production system to 3.0 for reasons irrelevant to this module, but I do have a local 3.0 system I could have looked at. My apologies
