### ISSUE TITLE
Custom variables in chat messages

### ISSUE THREAD

**Issue by rrr-iob** [bitfocus/companion-module-youtube-live#97]
Hey there, 
thanks for developing this companion module. 🙏🏼

When I use something like this the "Send message to live chat" action:
This is my text and this is $(internal:custom_variable).
... its posted in the chat exactly the same way, but the custom variable is not replaced with its value.

Is there a way to put in a custom variable to a chat message?
May be there is special formatting required?

----
I am using Companion 3.0.0+6049-stable-126f27e8 with macOS 12.6.8

**Comment by cyprient** [comment]
Hello @rrr-iob,
Which version of the module do you use?

**Comment by rrr-iob** [comment]
Hey @cyprient,
its v2.1.1 that comes with v3.0.0+6049-stable-126f27e8 of Companion.

**Comment by cyprient** [comment]
@rrr-iob The "Send message to live chat" action doesn't support variables in v2.1.1. The support was added in v2.3.0 which was recently released, and which is not yet included in Companion.

**Comment by rrr-iob** [comment]
@cyprient Is there a manual way to add this to Companion?

For example... could I simply replace this?
/Applications/Companion.app/Contents/Resources/bundled-modules/youtube-live

**Comment by cyprient** [comment]
@rrr-iob You can follow this documentation: https://github.com/bitfocus/companion-module-base/wiki

**Comment by rrr-iob** [comment]
Thanks for the link @cyprient ... tried it, could load the newer version but it won't start. The status stays at "unknown" and when I select the connection there is a animated bar and the text "Waiting for connection to start...". 🤷🏻‍♂️

**Comment by cyprient** [comment]
> Thanks for the link @cyprient ... tried it, could load the newer version but it won't start. The status stays at "unknown" and when I select the connection there is a animated bar and the text "Waiting for connection to start...". 🤷🏻‍♂️

@rrr-iob Did you build the module?

**Comment by rrr-iob** [comment]
> > Thanks for the link @cyprient ... tried it, could load the newer version but it won't start. The status stays at "unknown" and when I select the connection there is a animated bar and the text "Waiting for connection to start...". 🤷🏻‍♂️
> 
> @rrr-iob Did you build the module?

As a absolut noob I only copied the files to a folder and pointed to this in the Companion App. 🙈
If its necessary to build the module, I have no idea to do this. 🕳

**Comment by cyprient** [comment]
After investigating, there is a bug with the variable use in the "send message to live chat" action. A fix will soon be released.

**Comment by cyprient** [comment]
Fixed in #99
